Create ats user and group in the build environment
However the following error occurred.

  symlinked /usr/lib/debug/opt/trafficserver/lib64/libtsmgmt.so.6.2.0.debug to /usr/lib/debug/opt/trafficserver/lib64/libtsmgmt.so.debug
  24968 blocks
  + '[' '%{buildarch}' = noarch ']'
  + QA_CHECK_RPATHS=1
  + case "${QA_CHECK_RPATHS:-}" in
  + /usr/lib/rpm/check-rpaths
  *******************************************************************************
  *
  * WARNING: 'check-rpaths' detected a broken RPATH and will cause
  * 'rpmbuild'
  *          to fail. To ignore these errors, you can set the '$QA_RPATHS'
  *          environment variable which is a bitmask allowing the values
  *          below. The current value of QA_RPATHS is 0x0000.
  *
  *    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
  *               issue but are introducing redundant searchpaths without
  *               providing a benefit. They can also cause errors in
  *               multilib
  *               environments.
  *    0x0002 ... invalid RPATHs; these are RPATHs which are neither
  *    absolute
  *               nor relative filenames and can therefore be a SECURITY
  *               risk
  *    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
  *               SECURITY risk
  *    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
  *               RPATHs; this is just a minor issue but usually unwanted
  *    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
  *               and they cause unneeded work while loading libraries
  *    0x0020 ... an RPATH references '..' of an absolute path; this will
  *    break
  *               the functionality when the path before '..' is a symlink
  *
  *
  * Examples:
  * - to ignore standard and empty RPATHs, execute 'rpmbuild' like
  *   $ QA_RPATHS=$[ 0x0001|0x0010 ] rpmbuild my-package.src.rpm
  * - to check existing files, set $RPM_BUILD_ROOT and execute
  * check-rpaths like
  *   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
  *
  *******************************************************************************
  ERROR   0002: file '/opt/trafficserver/lib64/plugins/ssl_cert_loader.so'
  contains an invalid rpath '/opt/trafficserver/lib64' in
  [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/lib64/libtsmgmt.so.6.2.0'
  contains an invalid rpath '/opt/trafficserver/lib64' in
  [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_layout' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_via' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_sac' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_logcat' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_manager' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_line' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_ctl' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_cop' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_logstats' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_server' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  ERROR   0002: file '/opt/trafficserver/bin/traffic_crashlog' contains an
  invalid rpath '/opt/trafficserver/lib64' in [/opt/trafficserver/lib64]
  error: Bad exit status from /var/tmp/rpm-tmp.oZAmWC (%install)

  RPM build errors:
      Bad exit status from /var/tmp/rpm-tmp.oZAmWC (%install)
  The command '/bin/sh -c rpmbuild -bb ./SPECS/trafficserver.spec'
  returned a non-zero code: 1
  make: *** [all] Error 1